// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/";
  };
  "./layouts/main.jsx": {
    id: "layouts/main";
    page: "/";
  };
  "./pages/home.jsx": {
    id: "pages/home";
    page: "/";
  };
};